### ISSUE TITLE
Error Emulate Android Api 19

### ISSUE THREAD

**Issue by mauricionarcizo** [driftyco/ionic-conference-app#165]
Emulate the ionic-conference-app in the android emulator and use android 4.4.4.
When touched any tabs, to change the tab, show the following error:
<code>
"TypeError: Cannot redefine property: length
                                                                 at defineProperty (native)
                                                                 at Function.Object.defineProperty (file:///android_asset/www/build/js/app.bundle.js:2885:18)
                                                                 at String.localeCompare (native)
                                                                 at file:///android_asset/www/build/js/app.bundle.js:63895:25
                                                                 at Array.sort (native)
                                                                 at file:///android_asset/www/build/js/app.bundle.js:63892:31
                                                                 at Zone.run (file:///android_asset/www/build/js/app.bundle.js:2258:25)
                                                                 at Zone.run (file:///android_asset/www/build/js/app.bundle.js:17649:43)
                                                                 at zoneBoundFn (file:///android_asset/www/build/js/app.bundle.js:2235:27)
                                                                 at lib$es6$promise$$internal$$tryCatch (file:///android_asset/www/build/js/app.bundle.js:1483:18)", source: file:///android_asset/www/build/js/app.bundle.js (34190)
</code>

**Comment by brandyscarney** [comment]
Does this still happen with the latest code? Have you tested on an Android device/Genymotion or just the android emulator?

**Comment by mauricionarcizo** [comment]
Hi!
Yes, still happen with the latest code. I test just on the genymotion.

**Comment by jgw96** [comment]
@mauricionarcizo Hello! We have recently had a few new releases of Ionic 2. Would you mind testing again and see if you still have the issue?

**Comment by mauricionarcizo** [comment]
Similar error:
"EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot redefine property: length", source: file:///android_asset/www/build/js/app.bundle.js (31110)
04-29 11:38:29.361 4073-4073/io.ionic.conference I/chromium: [INFO:CONSOLE(31110)] "STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (31110)
04-29 11:38:29.361 4073-4073/io.ionic.conference I/chromium: [INFO:CONSOLE(31110)] "Error: Uncaught (in promise): TypeError: Cannot redefine property: length
                                                                 at resolvePromise (file:///android_asset/www/build/js/angular2-polyfills.js:602:32)
                                                                 at resolvePromise (file:///android_asset/www/build/js/angular2-polyfills.js:587:18)
                                                                 at file:///android_asset/www/build/js/angular2-polyfills.js:635:18
                                                                 at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/angular2-polyfills.js:423:38)
                                                                 at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/js/app.bundle.js:28189:41)
                                                                 at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/angular2-polyfills.js:422:43)
                                                                 at Zone.runTask (file:///android_asset/www/build/js/angular2-polyfills.js:320:48)
                                                                 at drainMicroTaskQueue (file:///android_asset/www/build/js/angular2-polyfills.js:541:36)
                                                                 at g (file:///android_asset/www/build/js/es6-shim.min.js:11:1946)
                                                                 at file:///android_asset/www/build/js/es6-shim.min.js:11:1876", source: file:///android_asset/www/build/js/app.bundle.js (31110)
04-29 11:38:29.361 4073-4073/io.ionic.conference I/chromium: [INFO:CONSOLE(528)] "Unhandled Promise rejection:", source: file:///android_asset/www/build/js/angular2-polyfills.js (528)
04-29 11:38:29.361 4073-4073/io.ionic.conference I/chromium: [INFO:CONSOLE(530)] "Error: Uncaught (in promise): TypeError: Cannot redefine property: length", source: file:///android_asset/www/build/js/angular2-polyfills.js (530)

Ionic info

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v5.0.0

**Comment by jgw96** [comment]
@mauricionarcizo and this is happening with android 4.4.4 right?

**Comment by mauricionarcizo** [comment]
@jgw96 Yes, I test on genymotion and android 4.4.4

**Comment by jgw96** [comment]
@mauricionarcizo Sorry should have asked this earlier, are you using the latest code for the conf app? ie: `git pull && npm install` ?

**Comment by mauricionarcizo** [comment]
Yes, I updated from git and do npm install

**Comment by michaeldesigaud** [comment]
I've got the same problem on genymotion and Android 4.4.4 but it works on genymotion and Android 5.0.0. It also work on real device with Android 5.1.X

**Comment by sfitzjava** [comment]
I'm running into this on KitKat 4.4 and am seeing several other posts related, but no work around or patches mentioned.   Any ideas how to address this?
My ionic info is:
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175 

Here are the links I found that seem to point to polyfills in the angular stack being the issue.
- [Angular 2 chatroom: I'm using old version of Chrome (35.0.1916.114)](https://gitter.im/angular/angular?at=56f0f284590ecaef713a7e99)
- [bug: number pipe not working on Chrome 34 or older (Cannot redefine property: length)
](https://github.com/angular/angular/issues/8188)

**Comment by jgw96** [comment]
Hello everyone! I am currently looking into this again. @sfitzjava So a blank ionic 2 template works fine for you, but as soon as you use the number pipe it breaks?

**Comment by sfitzjava** [comment]
@jgw96 yes when I run on an android device running kitkat 4.4
On 5.1 android device I do not have an issue with pipes.

**Comment by sfitzjava** [comment]
@jgw96  Added note, writing my own pipe works without any issues on the android kitkat 4.4 device.

**Comment by jgw96** [comment]
@sfitzjava would you mind trying on Android 4.4 with full crosswalk, not just crosswalk lite? Thanks!

**Comment by sfitzjava** [comment]
@jgw96  Had an issue with first try at full crosswalk, but when I increase min-sdk version to API 19 it would build and load.  Unfortunately it did not fix the error.  Still same exception on the pipes.
I reran without crosswalk and again with lite version again and all fail with android 4.4

Here is the console log exception from the base template (ie. no crosswalk of any type)

Unhandled Promise rejection: EXCEPTION: TypeError: Cannot redefine property: length in [{{priceVar|number:'1.0-0'}} in HomePage@9:12]
ORIGINAL EXCEPTION: TypeError: Cannot redefine property: length
ORIGINAL STACKTRACE:
TypeError: Cannot redefine property: length
    at defineProperty (native)
    at Function.Object.defineProperty (file:///android_asset/www/build/js/angular2-polyfills.js:1083:17)
    at freezeArray (v8/i18n:2004:8)
    at initializeLocaleList (v8/i18n:286:8)
    at resolveLocale (v8/i18n:1812:4)
    at initializeNumberFormat (v8/i18n:690:7)
    at new Object.defineProperty.value.ax (v8/i18n:796:8)
    at Function.NumberFormatter.format (file:///android_asset/www/build/js/app.bundle.js:27939:16)
    at Function.NumberPipe._format (file:///android_asset/www/build/js/app.bundle.js:5497:39)
    at DecimalPipe.transform (file:///android_asset/www/build/js/app.bundle.js:5546:27)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value: 
ChangeDetectionError
_context: _Context
_originalException: TypeError
_originalStack: "TypeError: Cannot redefine property: length↵    at defineProperty (native)↵    at Function.Object.defineProperty (file:///android_asset/www/build/js/angular2-polyfills.js:1083:17)↵    at freezeArray (v8/i18n:2004:8)↵    at initializeLocaleList (v8/i18n:286:8)↵    at resolveLocale (v8/i18n:1812:4)↵    at initializeNumberFormat (v8/i18n:690:7)↵    at new Object.defineProperty.value.ax (v8/i18n:796:8)↵    at Function.NumberFormatter.format (file:///android_asset/www/build/js/app.bundle.js:27939:16)↵    at Function.NumberPipe._format (file:///android_asset/www/build/js/app.bundle.js:5497:39)↵    at DecimalPipe.transform (file:///android_asset/www/build/js/app.bundle.js:5546:27)"
_wrapperMessage: "TypeError: Cannot redefine property: length in [{{priceVar|number:'1.0-0'}} in HomePage@9:12]"
_wrapperStack: "Error: TypeError: Cannot redefine property: length in [{{priceVar|number:'1.0-0'}} in HomePage@9:12]↵    at ChangeDetectionError.WrappedException (file:///android_asset/www/build/js/app.bundle.js:27861:31)↵    at new ChangeDetectionError (file:///android_asset/www/build/js/app.bundle.js:16140:16)↵    at AbstractChangeDetector._throwError (file:///android_asset/www/build/js/app.bundle.js:12996:21)↵    at AbstractChangeDetector.detectChangesInRecords (file:///android_asset/www/build/js/app.bundle.js:12881:18)↵    at AbstractChangeDetector.runDetectChanges (file:///android_asset/www/build/js/app.bundle.js:12851:14)↵    at AbstractChangeDetector._detectChangesInViewChildren (file:///android_asset/www/build/js/app.bundle.js:12951:18)↵    at AbstractChangeDetector.runDetectChanges (file:///android_asset/www/build/js/app.bundle.js:12855:14)↵    at AbstractChangeDetector.detectChanges (file:///android_asset/www/build/js/app.bundle.js:12840:73)↵    at ChangeDetectorRef_.detectChanges (file:///android_asset/www/build/js/app.bundle.js:13741:73)↵    at ViewController.willEnter (file:///android_asset/www/build/js/app.bundle.js:45410:22)"
context: (...)
location: "{{priceVar|number:'1.0-0'}} in HomePage@9:12"
message: (...)
originalException: (...)
originalStack: (...)
wrapperMessage: (...)
wrapperStack: (...)
__proto__: __

**Comment by pedroseac** [comment]
Having the exact same issue on Android 4.4

**Comment by rockertux** [comment]
It's an issue with Angular, not Ionic. Check it here: angular/angular#8188

**Comment by tamerbak** [comment]
In my case it was toLocaleDateString() javascript function, that causes this problem, I changed it and it was resolved.
You have to debug your code via livereload mode and locate the source of problem.
I did not find any explication about why it doesn't work on 4.4.4...

**Comment by jgw96** [comment]
Hello all! Because the built in Angular 2 pipes use the internationalization api they will not work on older versions of Android. To solve this issue you can build the app with crosswalk which will give you a modern, up to date version of the chrome webview that does support the intl api. If you are running Android 5.0 and higher it will work out of the box without crosswalk. SInce this is not an Ionic bug I will be closing this issue. Thanks for using Ionic!
