### ISSUE TITLE
Cannot find module 'colors'

### ISSUE THREAD

**Issue by aaronklaser** [driftyco/ionic-conference-app#167]
Aarons-MacBook-Pro:SyndicateApp aaronklaser$ ionic serve
Caught exception:
 Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/cli.js:2:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by brandyscarney** [comment]
Can you run `ionic info` and paste the output please?

**Comment by aaronklaser** [comment]
Same lol. Happens in both master and typescript branches. npm and ionic -g are up to date. 

Aarons-MacBook-Pro:SyndicateApp aaronklaser$ ionic info
Caught exception:
 Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/cli.js:2:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by brandyscarney** [comment]
What's the command you're running to install ionic? `npm install -g ionic@beta`?

**Comment by aaronklaser** [comment]
That work! It's weird though I literally JUST ran that on a different project. Does that need to be ran for each project? I thought global was global.

**Comment by brandyscarney** [comment]
No the `-g` should install it globally. Maybe something messed up on the install?

**Comment by brandyscarney** [comment]
I'm going to close this since it's working now. :smile:

**Comment by chansa1** [comment]
what did you guys do to fix it? i have tried npm install -g ionic@beta

**Comment by brandyscarney** [comment]
@chansa1 I wouldn't install the beta version of the CLI anymore. Can you try:

```
npm uninstall -g ionic
npm install -g ionic
```

If you run into any permission issues you may need to prefix the commands with `sudo`

**Comment by chansa1** [comment]
Thank you
