### ISSUE TITLE
Cannot find module 'babelify' 

### ISSUE THREAD

**Issue by lolaswift** [driftyco/ionic-conference-app#178]
#### Short description of the problem:
Not working on Windows 10

#### What behavior are you expecting?

**Steps to reproduce:**
1. run ionic serve

```
C:\Users\swift\ionic-conference-app>ionic serve

Running 'serve:before' gulp task before serve
[14:42:16] Starting 'sass'...
[14:42:16] Starting 'html'...
[14:42:16] Starting 'fonts'...
[14:42:16] Starting 'scripts'...
[14:42:16] Finished 'scripts' after 61 ms
[14:42:16] Finished 'html' after 105 ms
[14:42:16] Finished 'fonts' after 113 ms
[14:42:17] Finished 'sass' after 713 ms
[14:42:17] Starting 'watch'...
 ✗ Caught exception:
 Error: Cannot find module 'babelify' from 'C:\Users\swift\ionic-conference-app'
    at C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\swift\ionic-conference-app\node_modules\ionic-gulp-browserify-es2015\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which branch are you on?** master or typescript
master

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
C:\Users\swift\ionic-conference-app>ionic info

Your system information:

Cordova CLI: 6.1.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS:
Node Version: v4.4.2

**Comment by pjhartin** [comment]
From memory, I had the same issue. To resolve, I added 
`    "babel-preset-es2015": "^6.6.0"`
to devDependencies in the package.json.

Make sure to run `npm install` afterward, and you should be good to go.

**Comment by tlancina** [comment]
This happens if you have npm2, you can either update to npm3 or run `npm install babelify babel-plugin-transform-decorators-legacy babel-preset-es2015`.

Going to leave open as I'll add these in so that npm2 users don't have issues.

**Comment by tlancina** [comment]
Although I think the reason this was done originally was because npm2 users have really, really slow build times with Babel: https://github.com/driftyco/ionic-cli/issues/864#issuecomment-201702726.

**Comment by lolaswift** [comment]
@pjhartin: thx for the help but that didn't solve the issue

**Comment by lolaswift** [comment]
@tlancina: upgraded to npm 3 fixed the issue. Now I can "ionic serve" works. Millions of thanks~
@brandyscarney: thx as well brandy.

**Comment by brandyscarney** [comment]
@lolaswift Glad it's working for you! Going to close this. Thanks!

**Comment by tlancina** [comment]
This should now work for npm2 users with: https://github.com/driftyco/ionic-gulp-tasks/commit/8024997103827d66170b82443a7d1160540806ed (although builds will still be slower).
