### ISSUE TITLE
Can't find babelify module

### ISSUE THREAD

**Issue by villander** [driftyco/ionic-conference-app#182]
ionic-conference-app git:(master) ionic serve

Running 'serve:before' gulp task before serve 
[00:31:20] Starting 'clean'...
[00:31:20] Finished 'clean' after 8.48 ms
[00:31:20] Starting 'watch'...
[00:31:20] Starting 'sass'...
[00:31:20] Starting 'html'...
[00:31:20] Starting 'fonts'...
[00:31:20] Starting 'scripts'...
[00:31:20] Finished 'scripts' after 64 ms
[00:31:20] Finished 'html' after 90 ms
[00:31:20] Finished 'fonts' after 89 ms
[00:31:21] Finished 'sass' after 1.28 s
 ✗ Caught exception:
 Error: Cannot find module 'babelify' from '/Users/flama/Projects/ionic-conference-app'
    at /Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/flama/Projects/ionic-conference-app/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jbraun27** [comment]
More than likely, you need to update NPM which will include the babelify dependancies.  See Issue #180 Check your version of NPM by running `npm -v` , it should be v3.x. Run  `sudo npm install -g npm`  to update npm. and you should be good to go.

**Comment by villander** [comment]
Thanks @jbraun27
