### ISSUE TITLE
won't serve, no such file \typings\index.d.ts

### ISSUE THREAD

**Issue by ittasks** [driftyco/ionic-conference-app#241]
```
> Win10
> Cordova CLI: 6.3.0
> Ionic Framework Version: 2.0.0-beta.10
> Ionic CLI Version: 2.0.0-beta.35
> Ionic App Lib Version: 2.0.0-beta.19
> Node Version: v4.4.7
> 
```

downloaded zip (today)
runned npm install (got 2 warnings about deprecated stuff)
**trying ionic serve,** 
getting this error:

```

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> 
> c:\mobile\ionic-conference-app-master>ionic serve
> 
> Running 'serve:before' gulp task before serve
> [11:34:40] Starting 'clean'...
> [11:34:40] Finished 'clean' after 34 ms
> [11:34:40] Starting 'watch'...
> [11:34:40] Starting 'sass'...
> [11:34:41] Starting 'html'...
> [11:34:41] Starting 'fonts'...
> [11:34:41] Starting 'scripts'...
> [11:34:41] Finished 'html' after 124 ms
> [11:34:41] Finished 'scripts' after 129 ms
> [11:34:41] Finished 'fonts' after 138 ms
> [11:34:42] Finished 'sass' after 1.42 s
> Caught exception:
>  Error: ENOENT: no such file or directory, lstat 'c:\mobile\ionic-conference-app-master\typings\index.d.ts'
>     at Error (native)
>     at Object.fs.lstatSync (fs.js:839:18)
>     at Object.realpathSync (fs.js:1439:21)
>     at c:\mobile\ionic-conference-app-master\node_modules\tsify\index.js:58:38
>     at Array.map (native)
>     at DestroyableTransform.flush [as _flush] (c:\mobile\ionic-conference-app-master\node_modules\tsify\index.js:58:6)
>     at DestroyableTransform.<anonymous> (c:\mobile\ionic-conference-app-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
>     at DestroyableTransform.g (events.js:260:16)
>     at emitNone (events.js:67:13)
>     at DestroyableTransform.emit (events.js:166:7)
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues


```

**Comment by ittasks** [comment]
duplicate, closing
