### ISSUE TITLE
Build failed error on running $ ionic serve --lab

### ISSUE THREAD

**Issue by iAn-Pinto** [driftyco/ionic-conference-app#256]
#### Build failed error on running $ ionic serve --lab after running $ npm install:

Error: Module /Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/@angular/platform-browser-dynamic/esm/index.js does not export platformBrowserDynamic (imported by /Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/.tmp/app/main.dev.js)
    at Module.trace (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:7677:29)
    at ModuleScope.findDeclaration (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:7300:22)
    at CallExpression.bind (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5826:28)
    at /Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5151:50
    at MemberExpression.eachChild (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5168:5)
    at MemberExpression.bind (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5151:7)
    at MemberExpression.bind (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:6693:24)
    at /Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5151:50
    at CallExpression.eachChild (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5168:5)
    at CallExpression.bind (/Users/ianpinto/Documents/WebstormProjects/ionic-conference-app/node_modules/rollup/dist/rollup.js:5151:7)

[13:17:21]  sass started ...
[13:17:21]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

[13:17:21]  build dev failed:  Build failed

**System information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by ashutoshagg** [comment]
+1

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#83

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is a build related issue and not an issue specific to the conference app I have moved this issue to the app-scripts repo. Thanks!
