### ISSUE TITLE
Ionic serve not working

### ISSUE THREAD

**Issue by lingyilun** [driftyco/ionic-conference-app#320]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
> ionic-app-scripts serve

[13:35:18]  ionic-app-scripts 0.0.45
[13:35:19]  watch started ...
[13:35:19]  build dev started ...
[13:35:19]  clean started ...
[13:35:19]  clean finished in 2 ms
[13:35:19]  copy started ...
[13:35:19]  transpile started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8100
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1397:7
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\T2988\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! ionic-conference-app@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-conference-app@ ionic:serve script 'ionic-app-scrip
ts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-conference-app
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-conference-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-conference-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\T2988\Documents\ionic-2\ionic-conference-app\npm-debug.log

There was an error serving your Ionic application: There was an error with the s
pawned command: serve

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.0.0
Xcode version: Not installed

**Comment by lingyilun** [comment]
I updated my package.json

"scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },

It's working,this problem arises from my update ionic2
