### ISSUE TITLE
Can't resolve all parameters for RangeKnob

### ISSUE THREAD

**Issue by hentaicreep** [driftyco/ionic-conference-app#333]
hi，when i use `ionic serve` to run this project,it throw an error:
Error
Close
Runtime Error
Can't resolve all parameters for RangeKnob: (?).
Stack
Error: Can't resolve all parameters for RangeKnob: (?).
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/main.js:35973:19)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/main.js:35867:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:8100/build/main.js:35605:24)
    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:8100/build/main.js:35484:42)
    at http://localhost:8100/build/main.js:35750:87
    at http://localhost:8100/build/main.js:35665:99
    at Array.map (native)
    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:8100/build/main.js:35665:68)
    at RuntimeCompiler._loadModules (http://localhost:8100/build/main.js:75895:41)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8100/build/main.js:75865:35)
Ionic Framework: nightly
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.2.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by whwstart** [comment]
Error
Close
Runtime Error
Can't resolve all parameters for RangeKnob: (?).
Stack
Error: Can't resolve all parameters for RangeKnob: (?).
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/main.js:35973:19)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/main.js:35867:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:8100/build/main.js:35605:24)
    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:8100/build/main.js:35484:42)
    at http://localhost:8100/build/main.js:35750:87
    at http://localhost:8100/build/main.js:35665:99
    at Array.map (native)
    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:8100/build/main.js:35665:68)
    at RuntimeCompiler._loadModules (http://localhost:8100/build/main.js:75895:41)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8100/build/main.js:75865:35)
Ionic Framework: nightly
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.2.1
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1



me too

**Comment by brandyscarney** [comment]
Thanks for letting us know! I've just pushed a fix for this. Please pull (`git pull`) the latest code and run `npm install` and then `ionic serve`. Let me know if you are still having issues after that!

**Comment by brandyscarney** [comment]
I'm going to close this issue since it is an issue with the most recent `nightly` version of the framework and we are working on fixing it. :)

**Comment by hentaicreep** [comment]
ths~it work~
