### ISSUE TITLE
Cannot find module "localforage"

### ISSUE THREAD

**Issue by ywkobe** [driftyco/ionic-conference-app#373]
Runtime Error
Cannot find module "localforage"
Stack
Error: Cannot find module "localforage"
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at Object.<anonymous> (http://localhost:8100/build/main.js:134842:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:41165:67)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:119973:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:143426:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-19 at 3 19 46 pm" src="https://cloud.githubusercontent.com/assets/6577830/22123735/c61e8de4-de5a-11e6-85dd-763277b0ad86.png">

Thanks so much!

**Comment by edmundo096** [comment]
Anyone landing here should check https://github.com/ionic-team/ionic-storage/issues/128

Basically the issue may be either an `npm` version, an incorrect upgrading/updating of ionic and/or `node_modules` and/or the `packages-lock.json` file.
