### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by JayRaparla** [driftyco/ionic-conference-app#376]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1) git clone (the conference app)
2) npm install
3)this is the outcome
```
ionic-conference-app@ C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app
+-- ionicons@3.0.0
+-- rxjs@5.0.1
+-- sw-toolbox@3.4.0
+-- typescript@2.0.9
`-- zone.js@0.7.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JRAPARLA\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.3.0
npm ERR! path C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app\node_modules\.staging\ionic-angular-05e59c8a
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at destStatted (C:\Users\JRAPARLA\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Users\JRAPARLA\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app\node_modules\.staging\ionic-angular-05e59c8a' -> 'C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app\node_modules\ionic-angular'
npm ERR!  { Error
npm ERR!     at destStatted (C:\Users\JRAPARLA\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Users\JRAPARLA\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app\node_modules\.staging\ionic-angular-05e59c8a' -> 'C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app\node_modules\ionic-angular' parent: 'ionic-conference-app' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
C:\Users\JRAPARLA\Desktop\JayzProjects\ionic2\ionic-conference-app>ionic info

Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.4
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Can you try running `npm cache clean` and then `npm install` again?

**Comment by JayRaparla** [comment]
Tried the below

- npm cache clean and npm install -- failed
- updated npm to 4.4.4 and tried npm install -- failed again.

**Comment by JayRaparla** [comment]
I'm sorry.. this issue troubled me for a while but finally, I figured that it had something to do with my command prompt privileges. 
I deleted the cmd shortcut I had which had elevated privileges and re-tried the whole excercise and it seemed to work.
