### ISSUE TITLE
Help!Runtime Error:No provider for StatusBar

### ISSUE THREAD

**Issue by iSteveLiu** [driftyco/ionic-conference-app#382]
**A part of my code:**
````
import { StatusBar } from '@ionic-native/status-bar';
constructor(platform: Platform,private statusbar:StatusBar,private splashScreen:SplashScreen) {
    platform.ready().then(() => {
      this.statusbar.styleDefault();
    });
  }
````

Runtime Error
No provider for StatusBar!
**Stack**
````
Error
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at injectionError (http://localhost:8100/build/main.js:1511:86)
    at noProviderError (http://localhost:8100/build/main.js:1549:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:3051:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:3090:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:3022:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/main.js:2891:21)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:3856:52)
    at resolveDep (http://localhost:8100/build/main.js:11260:45)
    at createClass (http://localhost:8100/build/main.js:11123:91)
    at createDirectiveInstance (http://localhost:8100/build/main.js:10954:37)
    at createViewNodes (http://localhost:8100/build/main.js:12303:49)
    at createRootView (http://localhost:8100/build/main.js:12208:5)
    at callWithDebugContext (http://localhost:8100/build/main.js:13339:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/main.js:12800:12)
````
When i use SplashScreen,the same error occurred.
No provider for SplashScreen!

**Comment by heitoroliveiranet** [comment]
Hello!
Add "SplashScreen" into "providers" in your app.module.ts
example:

FILE: app.module.ts

import { StatusBar } from '@ionic-native/status-bar';
..................
 providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]

export class AppModule {}
