### ISSUE TITLE
Error: file to import not found or unreadable: ionic

### ISSUE THREAD

**Issue by intfrr** [driftyco/ionic-conference-app#56]
Hi, I have this problem. Any ideas?
```
$ ionic serve
∆ Compiling your SASS to CSS.
 Error: file to import not found or unreadable: ionic
Current dir: /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app/www/app/
    at Object.module.exports.renderSync (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/node-sass/lib/index.js:424:22)
    at Object.processSass (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/transpile.js:203:25)
    at Object.serve (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/serve.js:53:17)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:87:15
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
```

**Comment by intfrr** [comment]
Solved it with https://github.com/driftyco/ionic-conference-app/issues/50#issuecomment-153783378

But it still gives me this errors:

```
$ ionic serve
∆ Compiling your SASS to CSS.
√ Sass compiled to CSS.
∆ Running postcss and autoprefixer on compiled CSS.
∆ Compiling and bundling with Webpack...

√ Using your webpack.config.js file: /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/webpack.config.js
√ CSS processed to: /www/build/css/app.css
There were some errors with webpack
multi main
Module not found: Error: Cannot resolve module 'ionic/ionic' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
resolve module ionic/ionic in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/dragon/node_modules
    /Users/dragon/node_modules/ionic doesn't exist (module as directory)
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/ionic]
[/Users/dragon/node_modules/ionic]
 @ multi main,multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
resolve module web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
      resolve file
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
      resolve file
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/dragon/node_modules
    /Users/dragon/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/node_modules
      resolve file
        /Users/dragon/node_modules/web-animations.min doesn't exist
        /Users/dragon/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/node_modules/web-animations.min.ts doesn't exist
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.js]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.ts]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.js]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.ts]
[/Users/dragon/node_modules/web-animations.min]
[/Users/dragon/node_modules/web-animations.min]
[/Users/dragon/node_modules/web-animations.min.js]
[/Users/dragon/node_modules/web-animations.min.ts]
 @ multi main,./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/www/app
    Required in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/www/app/app.js
 @ multi main
 0=multi main
Module not found: Error: Cannot resolve module 'ionic/ionic' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
resolve module ionic/ionic in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/dragon/node_modules
    /Users/dragon/node_modules/ionic doesn't exist (module as directory)
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/ionic]
[/Users/dragon/node_modules/ionic]
 @ multi main, 1=multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
resolve module web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules
      resolve file
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
    /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules
      resolve file
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/dragon/node_modules
    /Users/dragon/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/dragon/node_modules
      resolve file
        /Users/dragon/node_modules/web-animations.min doesn't exist
        /Users/dragon/node_modules/web-animations.min.js doesn't exist
        /Users/dragon/node_modules/web-animations.min.ts doesn't exist
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.js]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/web-animations.min.ts]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.js]
[/Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/node_modules/ionic-framework/node_modules/web-animations.min.ts]
[/Users/dragon/node_modules/web-animations.min]
[/Users/dragon/node_modules/web-animations.min]
[/Users/dragon/node_modules/web-animations.min.js]
[/Users/dragon/node_modules/web-animations.min.ts]
 @ multi main, 2=./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/www/app
    Required in /Users/dragon/Documents/CSC/ASR/WORK/DCYTIC/PROJECTS/WEB/ISUM/IMPL/PROJECT/LOCAL/TEST/MOBILE/EXAMPLE/ionic/ionic-conference-app_2/www/app/app.js
 @ multi main
```

**Comment by intfrr** [comment]
It seems like if I substitute ```ionic/ionic``` by ```ionic-framework/js/ionic``` but now I get on the browser this error: 

```
ReferenceError: Can't find variable: System
(anonymous function)app.bundle.js:38027
__webpack_require__app.bundle.js:19
(anonymous function)app.bundle.js:50
__webpack_require__app.bundle.js:19
(anonymous function)app.bundle.js:39
(anonymous function)app.bundle.js:40
```

```
Refused to load the script 'http://localhost:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "script-src 'self' https://maps.googleapis.com/ https://maps.gstatic.com/ https://mts0.googleapis.com/ 'unsafe-inline' 'unsafe-eval'".
http://localhost:8100/build/js/Reflect.js.map
```
```
Failed to load resource: the server responded with a status of 404 (Not Found)    http://localhost:8100/build/js/Reflect.js.map
```

**Comment by talarari** [comment]
getting the same problem. this is pretty much the only demo i could find, would be great if it worked

**Comment by brandyscarney** [comment]
Unfortunately the conference app doesn't work with alpha.31, and the CLI only works with alpha.31 because of the change to the directory structure. We're working on improving the framework and getting a new release out. Sorry for the inconvenience, but this will be fixed when the framework improvements are completed.

**Comment by brandyscarney** [comment]
The conference app has been updated to alpha.32, please follow the below steps to get it working:

1. Install the latest version of the Ionic CLI (currently alpha.22): `npm install -g ionic@alpha`
2. Remove & and re-download the conference app: `git clone https://github.com/driftyco/ionic-conference-app`
3. Switch into that directory and run: `npm i`

Then you should be able to run `ionic serve` and other ionic commands. Please open a new issue if you find a different problem.
